blank_issues_enabled: false
contact_links:
  - name: Google Mobile Ads SDK Support Team
    url: https://developers.google.com/admob/support
    about: Official Google SDK support team responsible for solving bugs.
  - name: Google Mobile Ads SDK Documentation
    url: https://developers.google.com/admob/unity/start
    about: Official documentation for the Google Mobile Ads Unity plugin.
