#if UNITY_2021_3_OR_NEWER
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor.Android;

namespace GoogleMobileAds.Editor
{
    public class AndroidBuildSettings : UnityEditor.Editor
    {
        private const int MinimumAPILevel = 23;
        private const int TargetAPILevel = 34;
        private const string GradleTemplatePath = "Assets/Plugins/Android/gradleTemplate.properties";
        private const string MainGradleTemplatePath = "Assets/Plugins/Android/mainTemplate.gradle";
        private const string JetifierBlacklistEntry = "android.jetifier.blacklist=annotation-experimental-1.4.0.aar";
        private const string AndroidManifestPath = "Assets/Plugins/Android/AndroidManifest.xml";
        private const string GoogleMobileAdsManifestPath = "Assets/Plugins/Android/GoogleMobileAdsPlugin.androidlib/AndroidManifest.xml";
        private const string MinSdkVersionPattern = @"\s*android:minSdkVersion\s*=\s*""\d+""\s*";

        [MenuItem("Assets/Google Mobile Ads/Android/Set Recommended Build Settings")]
        public static void SetRecommendedAndroidBuildSettings()
        {
            EnableCustomGradleTemplates();
            SetMinimumApiLevel();
            SetTargetApiLevel();
            AddJetifierBlacklist();
            RemoveMinSdkVersionFromManifest(AndroidManifestPath);
            RemoveMinSdkVersionFromManifest(GoogleMobileAdsManifestPath);

            Debug.Log("Android build settings configured successfully for Unity Editor (2021+).");
        }

        private static void EnableCustomGradleTemplates()
        {
    #if UNITY_2022_1_OR_NEWER
            // For Unity 2022.1 and later, use the PlayerSettings properties
            if (!PlayerSettings.Android.customMainGradleTemplate)
            {
                PlayerSettings.Android.customMainGradleTemplate = true;
                Debug.Log("Enabled Custom Main Gradle Template.");
            }
            else
            {
                Debug.Log("Custom Main Gradle Template is already enabled.");
            }

            if (!PlayerSettings.Android.customGradlePropertiesTemplate)
            {
                PlayerSettings.Android.customGradlePropertiesTemplate = true;
                Debug.Log("Enabled Custom Gradle Properties Template.");
            }
            else
            {
                Debug.Log("Custom Gradle Properties Template is already enabled.");
            }
    #else
            // For Unity 2021 and earlier, check for the existence of the files
            if (!File.Exists(MainGradleTemplatePath))
            {
                // Create an empty mainTemplate.gradle file to enable the
                // custom template
                Directory.CreateDirectory(
                    Path.GetDirectoryName(MainGradleTemplatePath));
                File.WriteAllText(
                    MainGradleTemplatePath,
                    "// GENERATED BY UNITY. REMOVE THIS COMMENT TO UNLOCK MODIFICATIONS\n" +
                    "// Android Gradle Template\n\n" +
                    "buildscript {\n" +
                    "\trepositories {\n" +
                    "\t\tgoogle()\n" +
                    "\t\tjcenter()\n" +
                    "\t}\n" +
                    "\tdependencies {\n" +
                    "\t\tclasspath 'com.android.tools.build:gradle:3.6.0' " +
                    "// Recommended for Unity 2021\n" +
                    "\t}\n" +
                    "}\n\n" +
                    "allprojects {\n" +
                    "\trepositories {\n" +
                    "\t\tgoogle()\n" +
                    "\t\tjcenter()\n" +
                    "\t\tflatDir {\n" +
                    "\t\t\tdirs 'libs'\n" +
                    "\t\t}\n" +
                    "\t}\n" +
                    "}\n\n" +
                    "task clean(type: Delete) {\n" +
                    "\tdelete rootProject.buildDir\n" +
                    "}");
                Debug.Log($"Created basic {MainGradleTemplatePath} to enable " +
                          $"Custom Main Gradle Template. You might need to " +
                          $"adjust the Gradle version.");
            }
            else
            {
                Debug.Log($"{MainGradleTemplatePath} already exists.");
            }

            if (!File.Exists(GradleTemplatePath))
            {
                // Create an empty gradleTemplate.properties file to enable the custom template
                Directory.CreateDirectory(Path.GetDirectoryName(GradleTemplatePath));
                File.WriteAllText(GradleTemplatePath, "");
                Debug.Log($"Created empty {GradleTemplatePath} to enable Custom Gradle Properties Template.");
            }
            else
            {
                Debug.Log($"{GradleTemplatePath} already exists.");
            }
    #endif
        }

        private static void SetMinimumApiLevel()
        {
            PlayerSettings.Android.minSdkVersion = (AndroidSdkVersions)MinimumAPILevel;
            Debug.Log($"Minimum API Level set to: {MinimumAPILevel}");
        }

        private static void SetTargetApiLevel()
        {
            PlayerSettings.Android.targetSdkVersion = (AndroidSdkVersions)TargetAPILevel;
            Debug.Log($"Target API Level set to: {TargetAPILevel}");
        }

        private static void AddJetifierBlacklist()
        {
            if (!File.Exists(GradleTemplatePath))
            {
                Debug.LogError($"File not found: {GradleTemplatePath}." +
                                 $" Make sure 'Custom Gradle Properties Template' is enabled.");
                return;
            }

            string content = File.ReadAllText(GradleTemplatePath);
            if (!content.Contains(JetifierBlacklistEntry))
            {
                File.AppendAllText(GradleTemplatePath, "\n" + JetifierBlacklistEntry);
                Debug.Log($"Added '{JetifierBlacklistEntry}' to {GradleTemplatePath}");
            }
            else
            {
                Debug.Log($"'{JetifierBlacklistEntry}' already exists in {GradleTemplatePath}");
            }
        }

        private static void RemoveMinSdkVersionFromManifest(string manifestPath)
        {
            if (!File.Exists(manifestPath))
            {
                Debug.LogWarning($"AndroidManifest.xml not found at: " +
                                 $"{manifestPath}. Skipping minSDKVersion removal.");
               return;
            }

            string content = File.ReadAllText(manifestPath);
            string updatedContent = Regex.Replace(content, MinSdkVersionPattern, "");

            if (content != updatedContent)
            {
                File.WriteAllText(manifestPath, updatedContent);
                Debug.Log($"Removed 'android:minSdkVersion' from: {manifestPath}");
            }
            else
            {
                Debug.Log($"'android:minSdkVersion' not found in: {manifestPath}");
            }
        }
    }
}
#endif